### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by badele** [mondeja/pymarketcap#12]
Hi,

i receive this error when i use graps.currency function. I don't know if the `@staticmethod` decorator problem ?

If i run this line `print (coinmarketcap.graphs.currency("ETH",1515625200,1515711599))`

I receive the below error message

```
Traceback (most recent call last):
  File "import.py", line 248, in <module>
    importCoinsHistorical(coinsID)
  File "import.py", line 154, in importCoinsHistorical
    print (coinmarketcap.graphs.currency("ETH",1515625200,1515711599))
  File "/home/badele/private/projects/canalyzer/lib/python3.6/site-packages/pymarketcap/core.py", line 739, in currency
    url += self._add_start_end(url, start, end)
  File "/home/badele/private/projects/canalyzer/lib/python3.6/site-packages/pymarketcap/core.py", line 708, in _add_start_end
    start, end = self._parse_start_end(start, end)
NameError: name 'self' is not defined
```

**=== Some informations ===**

*Python version*
```
python -V
Python 3.6.4
```

*PIP version*
```
pip freeze | grep pymarketcap
pymarketcap==3.3.145
```

*Partial pymarketcap code section*
```
    @staticmethod
    def _add_start_end(url, start, end):
        """Internal function for add start and end to url"""
        start, end = self._parse_start_end(start, end)
        return "%s/%s/" % (start, end)
```

**Comment by mondeja** [comment]
Thanks, [it's solved](https://github.com/mondeja/pymarketcap/commit/c1e92764d6a6c2c4b9006ba2417fee423bc48e6d).
