### ISSUE TITLE
Session decoding issue

### ISSUE THREAD

**Issue by Treeless** [mondeja/pymarketcap#26]
Seems like there is an issue with session retrieval, as I keep getting this error: `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`, seems to be coming from this line: `currencies = self.session.get(url, proxies=self.proxies).json()`

Happens only when instantiating a new instance of pymarketcap.

Pymarketcap version: (3.3.158)
Python Version: 3.6.2

Lemme know if you need anything else.
I might be a hooligan and it's my own environment issue haha.

See full error below: 
---
`Traceback (most recent call last):
  File "prices.py", line 31, in <module>
    data = method_to_call(SYMBOL)
  File "c:\dev\SMSA\interfaces\crypto_info.py", line 25, in crypto_price
    cryptomarketcap = Pymarketcap() # Instance of coinmarketcap api
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\pymarketcap\core.py", line 71, in __init__
    self.correspondences = self._cache_symbols()
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\pymarketcap\core.py", line 104, in _cache_symbols
    currencies = self.session.get(url, proxies=self.proxies).json()
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\simplejson\__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\matt\AppData\Local\Programs\Python\Python36\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Sidelaunch** [comment]
I am having the same issue, tested on 3 machines

**Comment by mondeja** [comment]
Sorry but version `3.3.158` is not supported yet. Please update to `3.9.132`, it is hundreds times faster, has more methods and an asynchronous interface:
```
pip3 install pymarketcap
```

[You can see here an online documentation and demo](https://mybinder.org/v2/gh/mondeja/pymarketcap/master?filepath=docs%2Fsync_live.ipynb)
