### ISSUE TITLE
Update pymarketcap on pip

### ISSUE THREAD

**Issue by xmatthias** [mondeja/pymarketcap#27]
Hi,

any way to update pymarketcap on pypi anytime soon?

the current version there (3.3.158) seems to be unable to start now - the bug appears to be fixed in this repository - but it's not yet been pushed to pypi.

running python 3.6

```
from pymarketcap import Pymarketcap

pmc = Pymarketcap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymarketcap/core.py", line 71, in __init__
    self.correspondences = self._cache_symbols()
  File "/usr/local/lib/python3.6/site-packages/pymarketcap/core.py", line 104, in _cache_symbols
    currencies = self.session.get(url, proxies=self.proxies).json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks in advance

**Comment by mondeja** [comment]
Okei, the new version is already in Pypi.
