### ISSUE TITLE
Ticker Issue

### ISSUE THREAD

**Issue by Abolah** [mondeja/pymarketcap#28]
Hello, I updated the lib to last version but when I try to search for a specific coin here is the error I get

> DEBUG:
b''
b'https://files.coinmarketcap.com/generated/search/quick_search.json'
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    exc = cmc.ticker("BTC")
  File "pymarketcap\core.pyx", line 325, in pymarketcap.core.Pymarketcap.ticker
  File "pymarketcap\core.pyx", line 360, in pymarketcap.core.Pymarketcap.ticker
  File "pymarketcap\core.pyx", line 90, in pymarketcap.core.Pymarketcap.correspondences.__get__
  File "pymarketcap\core.pyx", line 142, in pymarketcap.core.Pymarketcap._cache_symbols_ids
  File "pymarketcap\core.pyx", line 135, in pymarketcap.core.Pymarketcap._quick_search
  File "pymarketcap\core.pyx", line 295, in pymarketcap.core.Pymarketcap._get
pymarketcap.errors.CoinmarketcapHTTPError: Status code -> 403 | Url -> https://files.coinmarketcap.com/generated/search/quick_search.json

here is the code:
`from pymarketcap import Pymarketcap
cmc = Pymarketcap(timeout=10)
exc = cmc.ticker("BTC")
print(exc)`

Can you help me ?

**Comment by mondeja** [comment]
It's fixed in the last commit. Coinmarketcap have been updated so the link fell down.
