### ISSUE TITLE
basic_sync_scraper example not working.

### ISSUE THREAD

**Issue by dgnsrekt** [mondeja/pymarketcap#45]
python3 basic_sync_scraper.py
Traceback (most recent call last):
  File "basic_sync_scraper.py", line 14, in <module>
    main()
  File "basic_sync_scraper.py", line 11, in main
    print(excs[0])  # Show first exchange
IndexError: list index out of range

**Comment by mondeja** [comment]
Thank you very much, it's fixed!

**Comment by mondeja** [comment]
Add examples testing to prevent this error.
